### ISSUE TITLE
Missing brackets in 03_logistic_regression_mnist_sol.py

### ISSUE THREAD

**Issue by csdaiwei** [chiphuyen/tf-stanford-tutorials#40]
at 03_logistic_regression_mnist_sol.py line 84-87

```
for i in range(n_batches):
    X_batch, Y_batch = mnist.test.next_batch(batch_size)
    accuracy_batch = sess.run([accuracy], feed_dict={X: X_batch, Y:Y_batch}) 
    total_correct_preds += accuracy_batch	
```

this yielded a TypeError on my running of python 3.5 tf 1.2 on windows
maybe add brackets as [accuracy_batch] would fix

**Comment by jkarimi91** [comment]
I am assuming that you are receiving the following error specifically:

```
Traceback (most recent call last):
  File "03_logistic_regression_mnist_sol.py", line 87, in <module>
    total_correct_preds += accuracy_batch	
TypeError: unsupported operand type(s) for +=: 'int' and 'list'
```

This error is a result of [line 86][1]:

`accuracy_batch = sess.run([accuracy], feed_dict={X: X_batch, Y:Y_batch})`

By passing `accuracy` to `sess.run()` as a list, we are telling `sess` to return a list which is assigned to `accuracy_batch`. Therefore, in [line 87][2], we end up trying to increment `total_correct_preds` by a list; this is not a valid operation in python.

Instead, what we really want is for `accuracy_batch` to be a single value, in this case an `int`. To do this, we simply pass a single node, rather than a list of nodes, to `sess.run()`. Therefore, [line 87][2] should be written as follows:

`accuracy_batch = sess.run(accuracy, feed_dict={X: X_batch, Y:Y_batch})`

[1]: https://github.com/chiphuyen/tf-stanford-tutorials/blob/master/examples/03_logistic_regression_mnist_sol.py#L86

[2]: https://github.com/chiphuyen/tf-stanford-tutorials/blob/master/examples/03_logistic_regression_mnist_sol.py#L87
